### ISSUE TITLE
Did you ever solve the dependency of PsGraph?

### ISSUE THREAD

**Issue by m1nkeh** [KevinMarquette/PSGraphPlus#22]
https://www.reddit.com/r/PowerShell/comments/79ebx1/how_do_i_get_module_dependencies_to_auto_download/

I have the same issue, and i need Az.Accounts..

Ty!

**Comment by KevinMarquette** [comment]
Yes. If it is a module, just specify it in the `RequiredModules`.

    RequiredModules   = 'Az.Accounts'

You can specify the name or a hashtable with the name and version. If you need multiple things, it can also take an array.

The trick is that the repository you upload it to also needs to have that module. In that post, I realized my mistake. I was specifying `ExternalModuleDependencies ` and I never should have done that. Using that key excludes modules from download. This is good for modules like `ActiveDirectory` that require an installer.

**Comment by m1nkeh** [comment]
Your last paragraph was the missing piece of the puzzle here. I went back and re-read the post.. sorted now.

Cheers! 😅
